#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel
export LD_LIBRARY_PATH=/lib:/usr/lib
#
#       Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

/sbin/hwclock -s


/bin/mount -a
/bin/mkdir -p /var/lib
/bin/mkdir -p /var/run
/bin/mkdir -p /var/log
/bin/mkdir -p /var/run/wpa_supplicant
/bin/mkdir -p /var/lib/hwclock
ln -s /tmp /var/run
hostname NEWLAND_CIT
# Input modules
insmod /driver/usb-datapipe.ko
# load wifi bin
/sbin/ifconfig wlan0 up &                                                  
sleep 1
echo 1 > /sys/class/firmware/1-1.2\:1.0/loading                            
cat  /lib/firmware/rt73.bin > /sys/class/firmware/1-1.2\:1.0/data           
echo 0 > /sys/class/firmware/1-1.2\:1.0/loading  
/sbin/ifconfig wlan0 down  
# mount sd
mount /dev/mmcblk0p1 /mnt/
# server
/sbin/klogd &
/sbin/syslogd -C64 &
/sbin/telnetd
/bin/vsftpd &

#self-test
cd /self-test
./citTest -a 
if [[ "$?" == "0" ]] ; then
    cd /bin/
    ./cit_sn
    cd /cit200
    ./main.lua&
else
    exit 1
fi
