#!/bin/sh
#
# usage: install [install options] [main.lua options]
# install options: -a    all (first remove current installation completely)
#                  -i    install only (do not start app)
#                  -r    reboot
# e.g:
# ./install -a -n
# Start main without ethernet network (re)configuration

if test $0 != /home/ftp/install -a -f /home/ftp/install; then
	chmod +x /home/ftp/install
	/home/ftp/install
	exit
fi

if ! cd /cit200; then
	exit
fi

./cit stop

if test "$1" == "-a"; then
	shift
	cp /cit200/cit.conf /mnt
	cd /cit200 && rm -rf *
	cp /mnt/cit.conf /cit200
	rm /mnt/cit.conf
	ifdown eth0
	ifdown wlan0
fi

#set -x
sync_file ( )
{
	if ! test -f $2; then
		echo "New file: $2"
		cp -af $1 $2
	else
		if ! diff $1 $2 > /dev/null; then 
			echo "Changed file: $2"
			cp -af $1 $2
		fi
	fi
}
	
# only copy files that are different:
tmpapp=/tmp/app
mkdir $tmpapp
cd $tmpapp
tar xf /home/ftp/app.tar
DIRS=`find . -type d`
cd /cit200
mkdir -p $DIRS
cd -
for f in `find . -type f`; do 
	sync_file "$tmpapp/$f" "/cit200/$f"
done
sync_file "/home/ftp/install" "/cit200/install"
chmod +x /cit200/install
cd /cit200
rm -rf $tmpapp

if test "$1" = "-r"; then
	sleep 2
	reboot
elif ! test "$1" = "-i"; then
	sleep 2
	set -x
	./cit -D start
fi

