#!/bin/bash

#set -x

CIT_IP_FILE=.cit.ip

function help
{
    echo "usage: put [-dq]|[-ip <nquire-ip>]"
	echo "When ip is omitted, the content of file ./$CIT_IP_FILE is used"
}

function test_ip
{
	if ! ping -c 1 $1; then
		help
		exit -1
	fi
}

if test "$1" = "-ip"; then
	IP=$2
	shift	
	shift
	test_ip ${IP}
	echo $IP > $CIT_IP_FILE
elif test "$1" = "-dq"; then
	echo "Discovering nquire..."
	IP=`nquire-discover.exe -1`
	if test -z "$IP"; then
		help
	    exit -1
	fi
else
	if test -f $CIT_IP_FILE; then
		IP=`cat $CIT_IP_FILE`
		test_ip ${IP}
	else
		help
	    exit -1
	fi		
fi

echo "Uploading to $IP"


# first with luac to detect compile errors
if ! make clean install; then
	exit
fi
make clean
rm -f app.tar

#if make TRACEON=true sys.so; then
	# don't compile, just copy!
	if make DEBUG=on all install app.tar;
	then
		pcit -ip $IP app.tar tools/install
	fi
#fi
