#!/bin/sh

ADDRESS=127.0.0.1
UDP_PORT=9000
TCP_PORT=9101

test_1()
{
	echo -en "\x1b\x42\x30"				# Font size 0
	echo -en "\x1b\x24"				# Clear screen
	echo -en "Mineral water"			# Text
	echo -en "\x0d"					# Carriage return
	echo -en "1 Ltr"				# Text
	echo -en "\x1b\x42\x31"				# Font size 1
	echo -en "\x1b\x2e\x38\x80 0.98\x03"		# Align text right bottom
}

test_2()
{
	echo -en "\x1b\x42\x30"				# Font size 0
	echo -en "\x1b\x24"				# Clear the screen
	echo -en "\x1b\x2e\x31Coca Cola 0.33Ltr\x03" 	# Text center - top
	echo -en "\x1b\x2c\x30\x45"			# Set pixel position (0,21)
	echo -en "\x1b\x2e\x3a\x802.69 (Crate)\x03"	# Align text to horizontal center
	echo -en "\x1b\x42\x31"				# Font size 1
	echo -en "\x1b\x2e\x37Special Offer !\x03"	# Text bottom center
}

test_3()
{
	echo -en "\x1b\x42\x30"				# Set font
	echo -en "\x1b\x25"				# Clear display
	echo -en "\x1b\x2e\x30Winner\x03" 		# Left top
	echo -en "\x1b\x2e\x32Winner\x03" 		# Right top
	echo -en "\x1b\x2e\x36Winner\x03" 		# Left bottom
	echo -en "\x1b\x2e\x38Winner\x03" 		# Right bottom
	echo -en "\x1b\x42\x31"				# Set font
	echo -en "\x1b\x2e\x34You Win!\x03" 		# Center
}

test_4()
{
	echo -en "\x1b\x42\x30"				# Set font
	echo -en "\x1b\x25"				# Clear display
	echo -en "\x1b\x2e\x30\x80\x03"	 		# Left top
}

test_5()
{
	echo -en "\x1b\xff\x01"				# Fake barcode scan
}

if [ "$1" == "udp" ]; then
	test_$2 | nc -u -w1 ${ADDRESS} ${UDP_PORT}
else
	test_$2 | nc -w1 ${ADDRESS} ${TCP_PORT}
fi

