#!/bin/sh
/bin/mount -a

#hostname NEWLAND_EP9307

hostname NEWLAND_EDDY
insmod /driver/usb-datapipe.ko
telnetd
/bin/vsftpd &
/sbin/ifconfig lo up
#/sbin/ifconfig eth0 up
#/sbin/ifconfig eth0 192.168.2.232 netmask 255.255.255.0
#/sbin/route add default gw 192.168.2.254

export LD_LIBRARY_PATH=/lib:/usr/lib
cd /cit200
./main.lua&
